# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  vuedockerplaygroundserver:
    image: vuedockerplaygroundserver
    build:
      context: .
      dockerfile: VueDockerPlayground.Server/Dockerfile
    ports:
      - 5104:5104
